# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          ''
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://sonal-saldanha.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Sonal Saldanha'
  url:            https://twitter.com/sonalsaldanha

# Custom vars
version:          1.0.0

github:
repo:			  github.com/sonal-saldanha/sonal-saldanha.github.io
